---
title: "About"
---

I am Ismail Bekar, an ecological researcher dedicated to unravelling the complexities of fire in our ecosystems.

My academic journey began at Hacettepe University in Ankara, where I graduated with a Bachelor's degree in Biology in 2013. During my undergraduate studies, I developed a keen interest in fire ecology, which led me to contribute to various related research projects.

Building on this foundational experience, I pursued and completed my Master's degree in Fire Ecology from 2013 to 2016. My research focused on understanding the complex interplay between anthropogenic and natural factors in shaping recent fire regimes in Mediterranean ecosystems. This research was conducted at the Fire Ecology and Seed Research Laboratory under the supervision of Prof. Dr. Çağatay Tavşanoğlu.

Towards the end of my Master's degree, I was awarded a Swiss Government Excellence Scholarship for my PhD studies. This opportunity prompted me to move to Zurich, where I started my PhD at ETH Zurich in the Forest Ecology Group.

Throughout my PhD studies, I focused on unravelling the complexity of fire regimes, using modelling approaches on fire occurrence and burned area. This research was carried out under the supervision of Prof. Harald Bugmann and Dr G. Boris Pezzatti.
